eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: sc-service-zuul

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: sc-service-ribbon
    api-b:
      path: /api-b/**
      serviceId: sc-service-feign